project:
  type: website
  output-dir: docs

website:
  title: "Agavoideae-PEPC"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: qc.qmd
        text: "Quality Checks"
      - href: map_align.qmd
        text: "Map & Align"

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: false



